//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirketOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BANKALAR
    {
        public short ID { get; set; }
        public string BANKAADI { get; set; }
        public string SUBE { get; set; }
        public string IBAN { get; set; }
        public string HESAPNO { get; set; }
        public string YETKILI { get; set; }
        public string TARIH { get; set; }
        public string HESAPTURU { get; set; }
        public Nullable<short> FIRMAID { get; set; }
        public string IL { get; set; }
        public string ILCE { get; set; }
        public string TELEFON { get; set; }
    
        public virtual TBL_FIRMA TBL_FIRMA { get; set; }
    }
}
