//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirketOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FATURABILGI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_FATURABILGI()
        {
            this.TBL_FATURADETAY = new HashSet<TBL_FATURADETAY>();
        }
    
        public int FATURABILGIID { get; set; }
        public string SERI { get; set; }
        public string SIRANO { get; set; }
        public string TARIH { get; set; }
        public string SAAT { get; set; }
        public string VERGIDAIRE { get; set; }
        public string ALICI { get; set; }
        public string TESLIMEDEN { get; set; }
        public string TESLIMALAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_FATURADETAY> TBL_FATURADETAY { get; set; }
    }
}
