//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirketOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MARKALAR
    {
        public int ID { get; set; }
        public Nullable<int> KATEGORI { get; set; }
        public string MARKA { get; set; }
    
        public virtual TBL_KATEGORILER TBL_KATEGORILER { get; set; }
    }
}
